### ISSUE TITLE
Performance bottlenecks

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#41]
- [ ] Repeatedly calling all_missing_properties takes time
- [ ] Querying the timeline database seems slow, even after a couple of calls. It waits for 25s. Is this endpoint blocked by others?

- [ ] Tree search counts is mainly slow in the backend, about 15s 
    - [ ] what is so slow? See https://docs.google.com/document/d/11U1sLlez8p7PHuC7OQcknC3CDMvAPA8-a_vACyyLTZE/edit
    - -> with all facets roughly 25-40s to load q-matrix and tree-search-counts, with 5 facets about 23s -> insignificant
    - [ ] Profile backend, where is most time used

**Comment by MRuecklCC** [comment]
I think most of these issues are resolved. I did no  notice any significant delay (more than a second) when querying the different endpoints.
