### ISSUE TITLE
Refactor internal data model for quality matrix

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#43]
Use 2D array, e.g., numpy or xarray
- [ ] Refactor API to convert from 2D array to json
- [ ] See https://github.com/openeduhub/metaqs-main/pull/42#discussion_r892158724

**Comment by MRuecklCC** [comment]
I know I was the one who was pushing this! 
But, after working a little bit on the front end side, I am no longer so sure of it: The angular table component that we use expects the data in a pretty denormalized format - essentially a list (the rows) of dictionaries (the columns within each row). This is pretty much as it is implemented right now. 
I hence propose to close as _wont't fix_

**Comment by RMeissnerCC** [comment]
I presume instead of fixing it, it makes sense to redesign required components by API-first and removing logic from the frontend. Thus: close this one and refactor altogether.
