### ISSUE TITLE
Update tree and more in background

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#44]
Redo every X seconds
- [ ] Query tree for new collections
  - [ ] use "https://vocabs.openeduhub.de/w3id.org/openeduhub/vocabs/oeh-topics/5e40e372-735c-4b17-bbf7-e827a5702b57.json"
  - [ ] Refactor: https://github.com/openeduhub/metaqs-main/pull/42#discussion_r891391870

To store state, use ... choose one
- [ ] context from starlette
- [ ] Redis
- [ ] global state of app

**Comment by MRuecklCC** [comment]
Resolved with #98. Last internal state is tracked here: #110
