### ISSUE TITLE
Refactor elasticsearch usage

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#45]
- [x] Avoid intention hiding
- [x] Refactor Search()
  - [x] e.g. for builder pattern, see https://github.com/openeduhub/metaqs-main/pull/42#discussion_r891408522
  - [x] Remove old usage, e.g. qbool or similar
  - [x] Unify add_base_match_filters and its older sibling
- [x] See https://github.com/openeduhub/metaqs-main/pull/51#issuecomment-1162864628

**Comment by MRuecklCC** [comment]
I think this can be considered as done with the other fixes in #113
