### ISSUE TITLE
Timeline for child nodes

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#46]
Currently, timeline is only stored for the root node

- [ ] How to distinguish to other nodes?

**Comment by MRuecklCC** [comment]
Timeline is now stored for all child collections (but not the root collection) via an application internal cron job.

If there is a cron job configured on one of the machines, then we should probably remove that job, as it is no longer necessary.

**Comment by MRuecklCC** [comment]
Removed the crontab on the dev machine.
