### ISSUE TITLE
MetaQS Widgets fail for Geography

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#61]
Choosing MetaQS for Geography caused fails for Marco

**Comment by MRuecklCC** [comment]
I can't check/reproduce this (neither dev nor prod) because I don't have the respective rights.

**Comment by MRuecklCC** [comment]
Cannot reproduce this on prod. all widgets load fine for me. However numbers are still off :exploding_head: 
![image](https://user-images.githubusercontent.com/104451100/192475945-a678a5e7-9b99-477b-b695-c1f6f95d8fe9.png)
![image](https://user-images.githubusercontent.com/104451100/192476048-59241fcc-89a9-4324-a2cc-0ab477245993.png)

**Comment by MRuecklCC** [comment]
Mostly resolved.
Also the screenshot above shows Materials for Chemie (not Geography) this might be purely frontend reload related.
 The (hopefully) last remaining cause for small discrepancies (not only for Geography) is discussed here: https://issues.edu-sharing.net/jira/browse/KBMBF-577
