### ISSUE TITLE
Search widgets and tables do not correspond

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metaqs-main#80]
- [ ] See https://issues.edu-sharing.net/jira/browse/SD_WLO-360
   - [x] Why is OER score not consistent between Score and CollectionTreeStats Widgets?
   - [ ] Why is the number of licenses in local and dev, as well as the small widgets and the CollectionTreeStats differently?
- [x] Make frontend point to staging in dev and redaktion in prod
- [x] If I edit something, does it disappear in the respective widget?
- [x] grey out score and indicate, that it is WIP
- [x] score and other tables show different OER content
- [x] Material without description yields collections - why?!
- [x] https://github.com/openeduhub/metaqs-main/issues/78
- [x] Rename form to mode and german words to english ones

**Comment by RMeissnerCC** [comment]
CollectionsTreeStats uses endpoints

- /validation/collections
- /validation
- /counts
- /tree

**Comment by RMeissnerCC** [comment]
MaterialsNoXYZ uses `pending-materials` endpoint

**Comment by MRuecklCC** [comment]
Now if I click on the edit button in I get forwarded to the staging environment, but there is nothing displayed there. I.e. the URI that is opened by the `MetaWidgetService.openNode` method seems to be wrong.

**Comment by RMeissnerCC** [comment]
mMmh, can you please supply an example? Because on my version it works :/

**Comment by RMeissnerCC** [comment]
OER content differed, partially because "total" from Elasticsearch differed from separate sum of doc_count - this is bizarre and I cannot explain it yet. Now, all tables use one and the same way to calculate OER ratios

**Comment by RMeissnerCC** [comment]
The base filters were missing in background elasticsearch query, thus finding more material, then pending-materials did.

**Comment by RMeissnerCC** [comment]
Material without description yielded collections, because it was set to point to collections in the frontend, see `widget-node-list.component.ts` Changed type there.

**Comment by RMeissnerCC** [comment]
Renamed Forms to mode, including in the frontend. All endpoints work again
